Spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://containers-us-west-138.railway.app:6530/railway
    username: postgres
    password: NzfygfNHsbiORtkbB5nP
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format: true