Spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:gerenciador
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format: true
  h2:
    console.enabled: true
